
import subprocess
import time

subprocess.run(['echo', 'Updating firewall settings for FreeIPA configuration'])
subprocess.run(['echo', 'Opening TCP/UDP 53 (DNS)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=53/tcp'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=53/udp'])
subprocess.run(['echo', 'Opening TCP 80 (HTTP)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=80/tcp'])
subprocess.run(['echo', 'Opening TCP 443 (HTTPS)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=443/tcp'])
subprocess.run(['echo', 'Opening TCP 389 (LDAP)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=389/tcp'])
subprocess.run(['echo', 'Opening TCP 636 (LDAPS)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=636/tcp'])
subprocess.run(['echo', 'Opening TCP/UDP 88/464 (KERBEROS)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=88/tcp'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=464/tcp'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=88/udp'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=464/udp'])
subprocess.run(['echo', 'Opening UDP 123 (NTP)'])
subprocess.run(['firewall-cmd', '--permanent', '--add-port=123/udp'])
subprocess.run(['echo', 'Stopping frewalld.service'])
subprocess.run(['echo', 'systemctl stop firewalld'])
time.sleep(1)
subprocess.run(['systemctl', 'stop', 'firewalld'])
subprocess.run(['echo', 'Starting firewalld.service'])
subprocess.run(['echo', 'systemctl start firewalld'])
time.sleep(1)
subprocess.run(['systemctl', 'start', 'firewalld'])
subprocess.run(['echo', 'Showing status of firewalld.service'])
subprocess.run(['echo', 'systemctl status firewalld'])
time.sleep(1)
subprocess.run(['systemctl', 'status', 'firewalld'])
subprocess.run(['echo', '.', '.'])
subprocess.run(['echo', 'Showing list of open ports on firewalld.service'])
subprocess.run(['echo', 'firewall-cmd --list-ports'])
time.sleep(1)
subprocess.run(['firewall-cmd', '--list-ports'])
subprocess.run(['echo', 'DONE!'])
